name: Build and Deploy React App to EC2
on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  # Job 1: Build the React app
  build:
    runs-on: ubuntu-latest
    name: Build React App


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
